#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-asciidoctorj-pdf
Version  : 1.5.0.alpha.16
Release  : 1
URL      : https://github.com/asciidoctor/asciidoctorj-pdf/archive/v1.5.0-alpha.16.tar.gz
Source0  : https://github.com/asciidoctor/asciidoctorj-pdf/archive/v1.5.0-alpha.16.tar.gz
Source1  : https://repo1.maven.org/maven2/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar
Source2  : https://repo1.maven.org/maven2/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-asciidoctorj-pdf-data = %{version}-%{release}
Requires: mvn-asciidoctorj-pdf-license = %{version}-%{release}
BuildRequires : buildreq-mvn
BuildRequires : gradle

%description
= AsciidoctorJ PDF: Asciidoctor
Alex Soto <https://github.com/lordofthejars[@lordofthejars]>; Dan Allen <https://github.com/mojavelinux[@mojavelinux]>
// Settings:
:compat-mode!:
:page-layout: base
:toc: macro
:toclevels: 2
ifdef::awestruct[:toclevels: 1]
:experimental:
//:table-caption!:
:source-language: java
:language: {source-language}
ifdef::env-github[:badges:]
// Aliases:
:dagger: &#8224;
// URIs:
ifdef::awestruct[:uri-docs: link:/docs]
ifndef::awestruct[:uri-docs: http://asciidoctor.org/docs]
:uri-asciidoctor: {uri-docs}/what-is-asciidoctor
:uri-asciidoctorj: https://github.com/asciidoctor/asciidoctorj
:uri-repo: https://github.com/asciidoctor/asciidoctorj-pdf
:uri-issues: {uri-repo}/issues
:uri-discuss: http://discuss.asciidoctor.org
:artifact-version: 1.5.0-alpha.13
:uri-maven-artifact-query: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.asciidoctor%22%20AND%20a%3A%22asciidoctorj%22%20AND%20v%3A%22{artifact-version}%22
:uri-maven-artifact-detail: http://search.maven.org/#artifactdetails%7Corg.asciidoctor%7Casciidoctorj%7C{artifact-version}%7Cjar
:uri-maven-artifact-file: http://search.maven.org/remotecontent?filepath=org/asciidoctor/asciidoctorj/{artifact-version}/asciidoctorj-{artifact-version}
:uri-bintray-artifact-query: https://bintray.com/asciidoctor/maven/asciidoctorj/view/general
:uri-bintray-artifact-detail: https://bintray.com/asciidoctor/maven/asciidoctorj/{artifact-version}/view
:uri-bintray-artifact-file: http://dl.bintray.com/asciidoctor/maven/org/asciidoctor/asciidoctorj/{artifact-version}/asciidoctorj-{artifact-version}
:uri-jruby-startup: http://github.com/jruby/jruby/wiki/Improving-startup-time
:uri-maven-guide: {uri-docs}/install-and-use-asciidoctor-maven-plugin
:uri-gradle-guide: {uri-docs}/install-and-use-asciidoctor-gradle-plugin
:uri-tilt: https://github.com/rtomayko/tilt
:uri-font-awesome: http://fortawesome.github.io/Font-Awesome
:uri-gradle: https://gradle.org

%package data
Summary: data components for the mvn-asciidoctorj-pdf package.
Group: Data

%description data
data components for the mvn-asciidoctorj-pdf package.


%package license
Summary: license components for the mvn-asciidoctorj-pdf package.
Group: Default

%description license
license components for the mvn-asciidoctorj-pdf package.


%prep
%setup -q -n asciidoctorj-pdf-1.5.0-alpha.16

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-asciidoctorj-pdf
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-asciidoctorj-pdf/LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar
/usr/share/java/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-asciidoctorj-pdf/LICENSE.txt
